### ISSUE TITLE
Age close to 0 for stellar particles in IllustrisTNG

### ISSUE THREAD

**Issue by AshieBurdon** [kateharborne/SimSpin#77]
In addition to stellar ages of 0 for particles in IllustrisTNG simulations causing an error in 'make_simspin_file', stellar ages close to 0 also cause problems. If ages are close but not equal to 0, 'make_simspin_file' will not throw up any errors and appear to complete normally, however the resulting file will be incomplete, and cause this error in 'build_datacube':
Error in stats::approx(x = simspin_data$wave, y = intrinsic_spectra, xout = observation$wave_seq,  :
  need at least two non-NA values to interpolate

In the case where scale factor = 1, it appears that GFM_StellarFormationTime values greater than 0.9996299, cause this issue.

**Comment by kateharborne** [comment]
Thank you for catching this @AshieBurdon!

The cause of this error was again due to a log10(0) = -Inf (as with Issue #76). This time, because the particle with a very small age fell into the first bin for the templates and the BC03 templates first bin is at Age = 0. As these bin labels were logged, the resulting bin was at index NA and this was not caught as a problem by the code until you tried to make an observation with a spectrum of NA's! 

This has now been solved with the pull of dev-ages #79. We've now implemented both:

- the fix of automatically adjusting any age=0 particles to have a very small, non-zero age, and 
- of updating the BC03 age labels to be a very small but non-zero number (currently the replacement placeholder value is 1e-9 Gyr).

With SimSpin v2.4.4, you should hopefully find that everything works out of the box without having to pre-adjust ages in the input files :+1:
